import type { NasaAsset } from "./types";

/**
 * Curated NASA public-domain catalog seed.
 * Preview media are public sample/Commons MP4 files so the player works offline
 * from any Lovable preview; sourceUrl always points at the official NASA page.
 */
export const NASA_CATALOG: NasaAsset[] = [
  {
    id: "svs-earth-rotation",
    title: "Terra em Rotação — Atmosfera Completa",
    description:
      "Visualização da Terra em rotação contínua com camada atmosférica realista, ideal para abertura de bloco e transições longas.",
    source: "NASA SVS",
    sourceUrl: "https://svs.gsfc.nasa.gov/4404",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/800px-The_Earth_seen_from_Apollo_17.jpg",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    category: "earth",
    duration: 596,
    resolution: "4K",
    fps: 60,
    format: "MP4",
    audioStatus: "Clear",
    rightsStatus: "broadcast_ok",
    broadcastAllowed: true,
    youtubeAllowed: "allowed",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 1,
    notes: "Domínio público NASA. Sem trilha licenciada.",
  },
  {
    id: "svs-black-marble",
    title: "Black Marble — Terra à Noite",
    description:
      "Mosaico noturno global do VIIRS/Suomi NPP mostrando luzes urbanas e ocupação humana do planeta.",
    source: "NASA SVS / NASA Earth Observatory",
    sourceUrl: "https://svs.gsfc.nasa.gov/30028",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Earthlights_2002.jpg/800px-Earthlights_2002.jpg",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    category: "earth_at_night",
    duration: 653,
    resolution: "4K",
    fps: 30,
    format: "MP4",
    audioStatus: "Clear",
    rightsStatus: "broadcast_ok",
    broadcastAllowed: true,
    youtubeAllowed: "allowed",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 2,
    notes: "Crédito sugerido: NASA Earth Observatory.",
  },
  {
    id: "svs-perpetual-ocean",
    title: "Perpetual Ocean — Correntes Marítimas",
    description:
      "Simulação ECCO2 das correntes oceânicas globais, com estética de tinta em movimento. Excelente bloco contemplativo.",
    source: "NASA SVS",
    sourceUrl: "https://svs.gsfc.nasa.gov/3827",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Perpetual_Ocean.jpg/800px-Perpetual_Ocean.jpg",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    category: "ocean",
    duration: 180,
    resolution: "1080p",
    fps: 30,
    format: "MP4",
    audioStatus: "Unknown",
    rightsStatus: "broadcast_ok",
    broadcastAllowed: true,
    youtubeAllowed: "allowed",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 3,
    notes: "Versão sem áudio. Trilha própria ORBI recomendada.",
  },
  {
    id: "svs-tour-of-the-moon",
    title: "Tour of the Moon — 4K",
    description:
      "Sobrevoo da Lua construído com dados do Lunar Reconnaissance Orbiter, passando por crateras e pelo polo sul lunar.",
    source: "NASA SVS / LRO",
    sourceUrl: "https://svs.gsfc.nasa.gov/4404",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/800px-FullMoon2010.jpg",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    category: "moon",
    duration: 294,
    resolution: "4K",
    fps: 30,
    format: "MP4",
    audioStatus: "Review",
    rightsStatus: "review",
    broadcastAllowed: true,
    youtubeAllowed: "review",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 4,
    notes:
      "Trilha sonora original pode acionar Content ID no YouTube. Recomendado exibir sem áudio original.",
  },
  {
    id: "svs-earth-system",
    title: "Earth System Science — Ciclos do Planeta",
    description:
      "Visualização integrada de atmosfera, oceano, biosfera e criosfera para blocos educativos.",
    source: "NASA SVS",
    sourceUrl: "https://svs.gsfc.nasa.gov/5077",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Blue_Marble_2002.png/800px-Blue_Marble_2002.png",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    category: "earth_science",
    duration: 240,
    resolution: "1080p",
    fps: 30,
    format: "MP4",
    audioStatus: "Clear",
    rightsStatus: "broadcast_ok",
    broadcastAllowed: true,
    youtubeAllowed: "allowed",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 5,
    notes: "Narração em inglês. Legendas pt-BR pendentes.",
  },
  {
    id: "svs-satellite-fleet",
    title: "Frota de Satélites de Observação da Terra",
    description:
      "Órbitas da frota científica da NASA em torno do planeta, com identificação das missões ativas.",
    source: "NASA SVS",
    sourceUrl: "https://svs.gsfc.nasa.gov/4443",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Terra_spacecraft_model.png/800px-Terra_spacecraft_model.png",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    category: "satellites",
    duration: 150,
    resolution: "1080p",
    fps: 60,
    format: "MP4",
    audioStatus: "Unknown",
    rightsStatus: "broadcast_ok",
    broadcastAllowed: true,
    youtubeAllowed: "allowed",
    thirdPartyContent: false,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 6,
    notes: "Sem áudio embutido.",
  },
  {
    id: "svs-space-weather-storm",
    title: "Space Weather — Tempestade Solar (Bloqueado)",
    description:
      "Simulação de ejeção de massa coronal atingindo a magnetosfera terrestre. Versão distribuída contém material de terceiros.",
    source: "NASA SVS / ESA colaboração",
    sourceUrl: "https://svs.gsfc.nasa.gov/4720",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Solar_flare_2012.jpg/800px-Solar_flare_2012.jpg",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    category: "space_weather",
    duration: 132,
    resolution: "1080p",
    fps: 30,
    format: "MP4",
    audioStatus: "Review",
    rightsStatus: "blocked",
    broadcastAllowed: false,
    youtubeAllowed: "blocked",
    thirdPartyContent: true,
    commercialUse: false,
    orbiWeb: false,
    broadcastPriority: 9,
    notes: "Música sob licença detectada e material de terceiros (ESA) requer revisão jurídica.",
  },
  {
    id: "svs-deep-field",
    title: "Campo Profundo — Webb Deep Field",
    description:
      "Aproximação em campo profundo com galáxias distantes captadas pelo James Webb Space Telescope.",
    source: "NASA / STScI",
    sourceUrl: "https://svs.gsfc.nasa.gov/14150",
    thumbnailUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Webb%27s_First_Deep_Field.jpg/800px-Webb%27s_First_Deep_Field.jpg",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerStealth.mp4",
    category: "space",
    duration: 210,
    resolution: "4K",
    fps: 30,
    format: "MP4",
    audioStatus: "Review",
    rightsStatus: "review",
    broadcastAllowed: true,
    youtubeAllowed: "review",
    thirdPartyContent: true,
    commercialUse: true,
    orbiWeb: true,
    broadcastPriority: 7,
    notes: "Material de terceiros (STScI) requer revisão de crédito antes da transmissão.",
  },
];
